sigla1 = "A1"
sigla2 = "A2"
sigla3 = "A3"
sigla4 = "A4"
sigla5 = "A5"
sigla6 = "A6"
sigla7 = "A7"
sigla8 = "A8"
sigla9 = "A9"
sigla10 = "A10"

A1 = "(p>(q>p))"
A2 = "(p>(q>r))>((p>q)>(p>r))"
A3 = "p>(q>(p∧q))"
A4 = "(p∧q)>p"
A5 = "(p∧q)>q"
A6 = "p>(p∨q)"
A7 = "q>(p∨q)"
A8 = "(p>r)>((q>r)>((p∨q)>r))"
A9 =  "(p>q)>((p>~q)>~p)"
A10 = "~~p>p"

